node { // <1>
	checkout scm // everything starts with beautiful source code

	def server = Artifactory.server MY-ID

    stage('Build') { // <2>
    	try {
    		sh 'mkdir build && cd build && cmake .. && cmake --build .'	
    	}
    	finally {
    		sh 'rm -rf build'
    	}
		
    }
    stage('Test') {
        sh 'ls build/src/libswftest.a'	// check whether library exists
    }
    stage('Deploy') {
        /* .. snip .. */
    }
}